name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger pipeline on main branch push

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install

      # Run tests
      - name: Run tests
        run: mvn test

  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run this job if the build is successful

    steps:
      - name: Trigger Jenkins Deployment Job
        run: |
          curl -X POST "http://<jenkins-server>/job/deploy-to-tomcat/buildWithParameters?token=<jenkins-token>&app_name=myApp"
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
