name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on main branch push

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install

      # Run tests
      - name: Run tests
        run: mvn test

  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run this job if the build is successful

    steps:
      # Trigger Jenkins Deployment Job
      - name: Trigger Jenkins Deployment Job
        run: |
          curl -u $JENKINS_USER:$JENKINS_API_TOKEN -X POST "https://cd34-109-55-249-75.ngrok-free.app/job/deploy-to-tomcat-2/buildWithParameters?token=my-deploy-token&app_name=myApp"
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
